// map of national park codes

let parkCodes = {
  acad: "Acadia",
  arch: "Arches",
  badl: "Badlands",
  bibe: "Big Bend",
  bisc: "Biscayne",
  blca: "Black Canyon of the Gunnison",
  brca: "Bryce Canyon",
  cany: "Canyonlands",
  care: "Capitol Reef",
  cave: "Carlsbad Caverns",
  coga: "Congaree",
  crla: "Crater Lake",
  cuva: "Cuyahoga Valley",
  dena: "Denali",
  deva: "Death Valley",
  drto: "Dry Tortugas",
  ever: "Everglades",
  gaar: "Gates of the Arctic",
  glac: "Glacier",
  glba: "Glacier Bay",
  grca: "Grand Canyon",
  grte: "Grand Teton",
  grba: "Great Basin",
  grsa: "Great Sand Dunes",
  grsm: "Great Smoky Mountains",
  grsp: "Great Sand Dunes",
  grte: "Grand Teton",
  gumo: "Guadalupe Mountains",
  hale: "Haleakala",
  havo: "Hawaii Volcanoes",
  hotw: "Hot Springs",
  indu: "Indiana Dunes",
  isro: "Isle Royale",
  jotr: "Joshua Tree",
  katm: "Katmai",
  kefj: "Kenai Fjords",
  klgo: "Kobuk Valley",
  lavo: "Lassen Volcanic",
  maca: "Mammoth Cave",
  meve: "Mesa Verde",
  moca: "Mount Rainier",
  noca: "North Cascades",
  olsp: "Olympic",
  pefo: "Petrified Forest",
  pinn: "Pinnacles",
  redw: "Redwood",
  romo: "Rocky Mountain",
  sagu: "Saguaro",
  seki: "Sequoia",
  shen: "Shenandoah",
  thro: "Theodore Roosevelt",
  vick: "Vickery Creek",
  viis: "Virgin Islands",
  vois: "Voyageurs",
  whsa: "White Sands",
  wrst: "Wrangell-St. Elias",
  yell: "Yellowstone",
  yose: "Yosemite",
  zion: "Zion",
  shil: "Shiloh",
  chis: "Chickasaw",
  chuc: "Chugach",
  cong: "Congaree",
  fobu: "Fort Bowie",
  chsc: "Chesapeake and Ohio Canal",
  labe: "Lake Berryessa",
  pore: "Portsmouth",
  cuis: "Cumberland Island",
  fomr: "Fort Matanzas",
  stea: "Steamtown",
  slbe: "Sleeping Bear Dunes",
  fofr: "Fort Frederica",
  piro: "Pictured Rock",
  jela: "Jean Lafitte",
  kimo: "Kings Mountain",
  fofa: "Fort Foote",
  fofu: "Fort Funston",
  fofl: "Fort Laramie",
  cowp: "Cowpens",
  peco: "Pea Ridge",
  knri: "Knife River",
  elma: "El Malpais",
  cech: "Chesapeake",
  grpo: "Great Plains",
  rich: "Richmond",
  edis: "Edison",
  buff: "Buffalo",
  pagr: "Palo Alto Battlefield",
  lyjo: "Lyndon B. Johnson",
  cana: "Cane River Creole",
  vall: "Valley Forge",
};

export default parkCodes;
